[package]
name = "sealer"
edition = "2021"

[lib]
name = "sealer"
crate-type = ["cdylib"]

[dependencies]
hex = "0.4"
jni = "0.21"
blake3 = "1.8"
ed25519-compact = "2.0"

[profile.release]
lto = true
strip = true
debug = false
panic = "abort"
opt-level = "z"