name: Build

on:
  push:
    branches: '**'
    paths-ignore:
      - '**/*.md'
    tags-ignore:
      - '**'
  pull_request:
    paths-ignore:
      - '**/*.md'

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"
      - name: Build with Gradle
        shell: bash
        run: ./gradlew zip
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: TS-Enhancer-Extreme-all-${{ matrix.os }}
          path: |
            module/build/outputs/release/*.zip
            module/build/outputs/debug/*.zip
          retention-days: 30
